
spring:
  # 当前文件
  profiles: dev
  
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_hello?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    
mybatis:
  #加载mybatis对应的mapper位置
  mapper-locations: classpath:com/wlb/springbootssm/dao/mapper/*.xml

  #加载mybatis别名设置
  type-aliases-package: com.wlb.springbootssm.entity

# 日志配置
logging:
  path:           #日志路径
  file: spring-boot-ssm\log\springboot-ssm.log #日志名称，这里用相对路径创建。可以不用path直接用file创建任何地方 
  level:
    # 指定路径配置log级别
    com:
      wlb: debug